version: '3.1'
services:
  # The nginx reverse proxy.
  # used for reverse proxying the API service and Web service.
  nginx:
    image: nvcr.io/nvidia/pytorch:23.04-py3
    command: git -C code clone --depth=1 https://github.com/hiyouga/ChatGLM-Efficient-Tuning.git
    volumes:
      - ../models/chatglm-6b:/app/ChatGLM-Efficient-Tuning/THUDM/chatglm-6b
      - ./code:/app/code
    stdin_open: true 
    tty: true
    ports:
      - 8090:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]